# permissions for end users to view s3buckets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: s3bucket-viewer-role
rules:
- apiGroups:
  - s3crdv1api.s3crdapiv1
  resources:
  - s3buckets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - s3crdv1api.s3crdapiv1
  resources:
  - s3buckets/status
  verbs:
  - get
